### PR TITLE
❄️ Snow ❄️ Animation

### PR DESCRIPTION
**Pull request by mrtrimble**
## Updates
- Added snowing animation (static background whenever `prefers-reduced-motion` is set)
- Updated Links to match throughout the site better
- Updated Charity details to highlight numbers a bit better

## Screenshots:

Snow Animation: (Updated)

https://user-images.githubusercontent.com/5217768/206326249-2a77d605-1dbe-4dd2-8d56-037cbb2bcfdc.mp4

Charity Details Numbers:
Screenshot 2022-12-06 at 8 36 51 PM

### CODE REVIEW

**Comment by a-trost** [comment]
Love the animation! My only thought is can we make the flakes smaller? Thinking maybe half or 1/3 the size? @mrtrimble

**Comment by leifniem** [comment]
Oh shoot, i added a snow parallax on my branch :S Sorry for not communicating that. If we want to we could find a way to combine both

**Comment by mrtrimble** [comment]
@leifniem nah, I'll kill this one - though there were a few other style changes here that I might want to keep.

**Comment by a-trost** [comment]
We were seeing some performance hits from the other snow that this one doesn't have, so I think we should pull this one in, along with the extra fixes to things like links. We can see if we can bring something from the other snow into what we merge in from this.

**Comment by mrtrimble** [comment]
Alright split this PR up into two separate ones:
- Link Styles: https://github.com/frontend-horse/holiday-show-page-2022/pull/50
- Snow Animation: https://github.com/frontend-horse/holiday-show-page-2022/pull/51

**Pull request closed without merging**
